# Generated by Django 6.0 on 2025-12-18 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tự động set khi tạo",
                        verbose_name="Ngày tạo",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tự động update khi lưu",
                        verbose_name="Ngày cập nhật",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_index=True,
                        help_text="Tên của contact",
                        max_length=50,
                        verbose_name="Tên",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True,
                        help_text="Họ và tên đệm của contact",
                        max_length=50,
                        verbose_name="Họ",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email phải là duy nhất trong hệ thống",
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Email không hợp lệ"
                            )
                        ],
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Format: +84xxxxxxxxx",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Số điện thoại phải đúng format. Format: '+99999999999'. Tối đa 10 chữ số.",
                                regex="^\\+?1?\\d{9,11}$",
                            )
                        ],
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Địa chỉ đầy đủ của contact",
                        null=True,
                        verbose_name="Địa chỉ",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Ghi chú thêm về contact này",
                        null=True,
                        verbose_name="Ghi chú",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Đánh dấu contact quan trọng",
                        verbose_name="Yêu thích",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete: False = đã xóa",
                        verbose_name="Hoạt động",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liên hệ",
                "verbose_name_plural": "Các liên hệ",
                "db_table": "contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Tự động set khi tạo",
                        verbose_name="Ngày tạo",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Tự động update khi lưu",
                        verbose_name="Ngày cập nhật",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Tên nhóm phải là duy nhất trong hệ thống",
                        max_length=100,
                        unique=True,
                        verbose_name="Tên nhóm",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("FAMILY", "Gia đình"),
                            ("FRIEND", "Bạn bè"),
                            ("WORK", "Công việc"),
                            ("CUSTOMER", "Khách hàng"),
                            ("OTHER", "Khác"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=10,
                        verbose_name="Loại nhóm",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Mô tả chi tiết về nhóm này",
                        null=True,
                        verbose_name="Mô tả",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhóm liên hệ",
                "verbose_name_plural": "Các nhóm liên hệ",
                "db_table": "contact_groups",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_group_name"),
                    models.Index(fields=["group_type"], name="idx_group_type"),
                    models.Index(fields=["-created_at"], name="idx_group_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Vai trò của contact trong nhóm này (VD: Admin, Member)",
                        max_length=50,
                        null=True,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Thời điểm contact được thêm vào nhóm",
                        verbose_name="Ngày tham gia",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="Contact thuộc nhóm này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="contacts.contact",
                        verbose_name="Liên hệ",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Nhóm chứa contact này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="contacts.contactgroup",
                        verbose_name="Nhóm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thành viên nhóm",
                "verbose_name_plural": "Các thành viên nhóm",
                "db_table": "contact_group_memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Các nhóm mà contact này thuộc về",
                related_name="contacts",
                through="contacts.ContactGroupMembership",
                to="contacts.contactgroup",
                verbose_name="Các nhóm",
            ),
        ),
        migrations.AddIndex(
            model_name="contactgroupmembership",
            index=models.Index(
                fields=["contact", "group"], name="idx_membership_contact_group"
            ),
        ),
        migrations.AddIndex(
            model_name="contactgroupmembership",
            index=models.Index(fields=["-joined_at"], name="idx_membership_joined"),
        ),
        migrations.AlterUniqueTogether(
            name="contactgroupmembership",
            unique_together={("contact", "group")},
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["last_name", "first_name"], name="idx_contact_name"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="idx_contact_email"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["is_favorite"], name="idx_contact_favorite"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["is_active"], name="idx_contact_active"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["-created_at"], name="idx_contact_created"),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone__isnull", False)),
                fields=("first_name", "last_name", "phone"),
                name="unique_contact_name_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(("email__contains", "@")), name="check_email_format"
            ),
        ),
    ]
